/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#090e18',
        'on-background': '#eaedfd',
        surface: '#090e18',
        'surface-dim': '#090e18',
        'surface-bright': '#252c3c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#0e131f',
        'surface-container': '#141a26',
        'surface-container-high': '#19202d',
        'surface-container-highest': '#1f2635',
        'surface-variant': '#1f2635',
        primary: '#81ecff',
        'primary-dim': '#00d4ec',
        'on-primary': '#005762',
        'on-primary-container': '#004d57',
        outline: '#717582',
        'outline-variant': '#434854',
        'on-surface': '#eaedfd',
        'on-surface-variant': '#a7abb9',
        secondary: '#d7e5ec',
        'secondary-container': '#3c494f',
        'on-secondary': '#46545a',
        tertiary: '#d2fffe',
        'tertiary-dim': '#55e3e3',
        error: '#ff716c',
        'error-container': '#9f0519',
        'inverse-surface': '#f9f9ff',
        'inverse-on-surface': '#505561',
        'inverse-primary': '#006976',
        'surface-tint': '#81ecff',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        label: ['"Inter"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      animation: {
        'glow-pulse': 'glow-pulse 4s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
      },
      keyframes: {
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.7' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
